// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.example.generic_paradigm.protobuf;

public final class StudentSerializable {
  private StudentSerializable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sex = 2;</code>
     * @return The sex.
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 2;</code>
     * @return The bytes for sex.
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course> 
        getCoursesList();
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    com.example.generic_paradigm.protobuf.StudentSerializable.Course getCourses(int index);
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    int getCoursesCount();
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    java.util.List<? extends com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder> 
        getCoursesOrBuilderList();
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder getCoursesOrBuilder(
        int index);
  }
  /**
   * <pre>
   *注意proto文件不能喝 java_outer_classname 名字一样，否则无法编译成功
   * </pre>
   *
   * Protobuf type {@code Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      sex_ = "";
      courses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                courses_ = new java.util.ArrayList<com.example.generic_paradigm.protobuf.StudentSerializable.Course>();
                mutable_bitField0_ |= 0x00000001;
              }
              courses_.add(
                  input.readMessage(com.example.generic_paradigm.protobuf.StudentSerializable.Course.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.generic_paradigm.protobuf.StudentSerializable.Student.class, com.example.generic_paradigm.protobuf.StudentSerializable.Student.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 2;
    private volatile java.lang.Object sex_;
    /**
     * <code>string sex = 2;</code>
     * @return The sex.
     */
    @java.lang.Override
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 2;</code>
     * @return The bytes for sex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int COURSES_FIELD_NUMBER = 4;
    private java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course> courses_;
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course> getCoursesList() {
      return courses_;
    }
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder> 
        getCoursesOrBuilderList() {
      return courses_;
    }
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    @java.lang.Override
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    @java.lang.Override
    public com.example.generic_paradigm.protobuf.StudentSerializable.Course getCourses(int index) {
      return courses_.get(index);
    }
    /**
     * <pre>
     * required 指定该字段必须赋值 禁止为空
     * </pre>
     *
     * <code>repeated .Course courses = 4;</code>
     */
    @java.lang.Override
    public com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder getCoursesOrBuilder(
        int index) {
      return courses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sex_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sex_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        output.writeMessage(4, courses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sex_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sex_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, courses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.generic_paradigm.protobuf.StudentSerializable.Student)) {
        return super.equals(obj);
      }
      com.example.generic_paradigm.protobuf.StudentSerializable.Student other = (com.example.generic_paradigm.protobuf.StudentSerializable.Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSex()
          .equals(other.getSex())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getCoursesList()
          .equals(other.getCoursesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getCoursesCount() > 0) {
        hash = (37 * hash) + COURSES_FIELD_NUMBER;
        hash = (53 * hash) + getCoursesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.generic_paradigm.protobuf.StudentSerializable.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *注意proto文件不能喝 java_outer_classname 名字一样，否则无法编译成功
     * </pre>
     *
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.example.generic_paradigm.protobuf.StudentSerializable.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.generic_paradigm.protobuf.StudentSerializable.Student.class, com.example.generic_paradigm.protobuf.StudentSerializable.Student.Builder.class);
      }

      // Construct using com.example.generic_paradigm.protobuf.StudentSerializable.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCoursesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        sex_ = "";

        age_ = 0;

        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Student getDefaultInstanceForType() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Student build() {
        com.example.generic_paradigm.protobuf.StudentSerializable.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Student buildPartial() {
        com.example.generic_paradigm.protobuf.StudentSerializable.Student result = new com.example.generic_paradigm.protobuf.StudentSerializable.Student(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.age_ = age_;
        if (coursesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            courses_ = java.util.Collections.unmodifiableList(courses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.courses_ = courses_;
        } else {
          result.courses_ = coursesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.generic_paradigm.protobuf.StudentSerializable.Student) {
          return mergeFrom((com.example.generic_paradigm.protobuf.StudentSerializable.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.generic_paradigm.protobuf.StudentSerializable.Student other) {
        if (other == com.example.generic_paradigm.protobuf.StudentSerializable.Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (coursesBuilder_ == null) {
          if (!other.courses_.isEmpty()) {
            if (courses_.isEmpty()) {
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoursesIsMutable();
              courses_.addAll(other.courses_);
            }
            onChanged();
          }
        } else {
          if (!other.courses_.isEmpty()) {
            if (coursesBuilder_.isEmpty()) {
              coursesBuilder_.dispose();
              coursesBuilder_ = null;
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coursesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCoursesFieldBuilder() : null;
            } else {
              coursesBuilder_.addAllMessages(other.courses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.generic_paradigm.protobuf.StudentSerializable.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.generic_paradigm.protobuf.StudentSerializable.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 2;</code>
       * @return The sex.
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 2;</code>
       * @return The bytes for sex.
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 2;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 2;</code>
       * @param value The bytes for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course> courses_ =
        java.util.Collections.emptyList();
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          courses_ = new java.util.ArrayList<com.example.generic_paradigm.protobuf.StudentSerializable.Course>(courses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.generic_paradigm.protobuf.StudentSerializable.Course, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder, com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder> coursesBuilder_;

      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course> getCoursesList() {
        if (coursesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(courses_);
        } else {
          return coursesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public int getCoursesCount() {
        if (coursesBuilder_ == null) {
          return courses_.size();
        } else {
          return coursesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course getCourses(int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);
        } else {
          return coursesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder setCourses(
          int index, com.example.generic_paradigm.protobuf.StudentSerializable.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.set(index, value);
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder setCourses(
          int index, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.set(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder addCourses(com.example.generic_paradigm.protobuf.StudentSerializable.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder addCourses(
          int index, com.example.generic_paradigm.protobuf.StudentSerializable.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(index, value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder addCourses(
          com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder addCourses(
          int index, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder addAllCourses(
          java.lang.Iterable<? extends com.example.generic_paradigm.protobuf.StudentSerializable.Course> values) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, courses_);
          onChanged();
        } else {
          coursesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder clearCourses() {
        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public Builder removeCourses(int index) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.remove(index);
          onChanged();
        } else {
          coursesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder getCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder getCoursesOrBuilder(
          int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);  } else {
          return coursesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public java.util.List<? extends com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder> 
           getCoursesOrBuilderList() {
        if (coursesBuilder_ != null) {
          return coursesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(courses_);
        }
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder addCoursesBuilder() {
        return getCoursesFieldBuilder().addBuilder(
            com.example.generic_paradigm.protobuf.StudentSerializable.Course.getDefaultInstance());
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder addCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().addBuilder(
            index, com.example.generic_paradigm.protobuf.StudentSerializable.Course.getDefaultInstance());
      }
      /**
       * <pre>
       * required 指定该字段必须赋值 禁止为空
       * </pre>
       *
       * <code>repeated .Course courses = 4;</code>
       */
      public java.util.List<com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder> 
           getCoursesBuilderList() {
        return getCoursesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.generic_paradigm.protobuf.StudentSerializable.Course, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder, com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder> 
          getCoursesFieldBuilder() {
        if (coursesBuilder_ == null) {
          coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.generic_paradigm.protobuf.StudentSerializable.Course, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder, com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder>(
                  courses_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          courses_ = null;
        }
        return coursesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.example.generic_paradigm.protobuf.StudentSerializable.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.generic_paradigm.protobuf.StudentSerializable.Student();
    }

    public static com.example.generic_paradigm.protobuf.StudentSerializable.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.generic_paradigm.protobuf.StudentSerializable.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CourseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Course)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>float score = 2;</code>
     * @return The score.
     */
    float getScore();
  }
  /**
   * <pre>
   * 一个proto文件中可以同时定义多个message类型，生成代码时根据生成代码的目标语言不通，处理的方式也不太一样
   * </pre>
   *
   * Protobuf type {@code Course}
   */
  public static final class Course extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Course)
      CourseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Course.newBuilder() to construct.
    private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Course() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Course();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Course(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 21: {

              score_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Course_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.generic_paradigm.protobuf.StudentSerializable.Course.class, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <code>float score = 2;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        output.writeFloat(2, score_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (java.lang.Float.floatToRawIntBits(score_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.generic_paradigm.protobuf.StudentSerializable.Course)) {
        return super.equals(obj);
      }
      com.example.generic_paradigm.protobuf.StudentSerializable.Course other = (com.example.generic_paradigm.protobuf.StudentSerializable.Course) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.generic_paradigm.protobuf.StudentSerializable.Course prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 一个proto文件中可以同时定义多个message类型，生成代码时根据生成代码的目标语言不通，处理的方式也不太一样
     * </pre>
     *
     * Protobuf type {@code Course}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Course)
        com.example.generic_paradigm.protobuf.StudentSerializable.CourseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Course_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Course_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.generic_paradigm.protobuf.StudentSerializable.Course.class, com.example.generic_paradigm.protobuf.StudentSerializable.Course.Builder.class);
      }

      // Construct using com.example.generic_paradigm.protobuf.StudentSerializable.Course.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        score_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.internal_static_Course_descriptor;
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course getDefaultInstanceForType() {
        return com.example.generic_paradigm.protobuf.StudentSerializable.Course.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course build() {
        com.example.generic_paradigm.protobuf.StudentSerializable.Course result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.generic_paradigm.protobuf.StudentSerializable.Course buildPartial() {
        com.example.generic_paradigm.protobuf.StudentSerializable.Course result = new com.example.generic_paradigm.protobuf.StudentSerializable.Course(this);
        result.name_ = name_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.generic_paradigm.protobuf.StudentSerializable.Course) {
          return mergeFrom((com.example.generic_paradigm.protobuf.StudentSerializable.Course)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.generic_paradigm.protobuf.StudentSerializable.Course other) {
        if (other == com.example.generic_paradigm.protobuf.StudentSerializable.Course.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.generic_paradigm.protobuf.StudentSerializable.Course parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.generic_paradigm.protobuf.StudentSerializable.Course) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 2;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 2;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Course)
    }

    // @@protoc_insertion_point(class_scope:Course)
    private static final com.example.generic_paradigm.protobuf.StudentSerializable.Course DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.generic_paradigm.protobuf.StudentSerializable.Course();
    }

    public static com.example.generic_paradigm.protobuf.StudentSerializable.Course getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Course>
        PARSER = new com.google.protobuf.AbstractParser<Course>() {
      @java.lang.Override
      public Course parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Course(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Course> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Course> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.generic_paradigm.protobuf.StudentSerializable.Course getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Course_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Course_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"K\n\007Student\022\014\n\004name\030\001 \001(\t\022" +
      "\013\n\003sex\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\030\n\007courses\030\004 \003" +
      "(\0132\007.Course\"%\n\006Course\022\014\n\004name\030\001 \001(\t\022\r\n\005s" +
      "core\030\002 \001(\002B<\n%com.example.generic_paradi" +
      "gm.protobufB\023StudentSerializableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Name", "Sex", "Age", "Courses", });
    internal_static_Course_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Course_descriptor,
        new java.lang.String[] { "Name", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
